[package]
name = "riscv64-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
strum = "0.24"
strum_macros = "0.24"
chrono = "0.4"
sdl2 = "0.35"
ring-channel = "0.11"

[profile.release]
# lto = true

