[package]
name = "riscv64-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
strum = "0.24"
strum_macros = "0.24"
chrono = "0.4"
sdl2 = {version="0.35" }
ring-channel = "0.11"
# colored = "2"
hashbrown = "0.13.2"
bitfield-struct = "0.3.2"
llvm-sys = "150"
enum_dispatch = "0.3.11"
crossbeam-channel = "0.5.7"

[features]
# default = ["rv_debug_trace","support_am"]
# default = ["support_am"]
rv_debug_trace = []
support_am = []


[profile.release]
# lto = true
# debug = true
# opt-level = 2
